### PR TITLE
Checklable views fix

### LINKED ISSUE #22: ListView.CHOICE_MODE_MULTIPLE_MODAL issue
I'm using the ListView.CHOICE_MODE_MULTIPLE_MODAL with AbsListView.MultiChoiceModeListener.

It works great, the items on the listview get checked on LongClick.

But when using it with the SwipeActionAdapter, the views don't change to the checked state although the onItemCheckedStateChanged is fired.

### PR DESCRIPTION
**Pull request by leosimas**
Call the setChecked when the content view implements Checkable.
Trying to fix #22

### CODE REVIEW

File: library/src/main/java/com/wdullaer/swipeactionadapter/SwipeViewGroup.java [hunk 1]
```diff
@@ -194,4 +196,22 @@ public boolean onTouchEvent(@NonNull MotionEvent ev) {
         // Finish the swipe gesture: our parent will no longer do it if this function is called
         return swipeTouchListener.onTouch(this, ev);
     }
+
+    @Override
+    public void setChecked(boolean checked) {
+        this.checked = checked;
+        if ( contentView != null && contentView instanceof Checkable ) {
```
Comment (wdullaer) [inline library/src/main/java/com/wdullaer/swipeactionadapter/SwipeViewGroup.java]: Nitpicking mode: can you remove the spaces after the if brackets?

File: library/src/main/java/com/wdullaer/swipeactionadapter/SwipeViewGroup.java [hunk 2]
```diff
@@ -194,4 +196,22 @@ public boolean onTouchEvent(@NonNull MotionEvent ev) {
...
+    }
+
+    @Override
+    public boolean isChecked() {
+        return checked;
+    }
+
+    @Override
+    public void toggle() {
+        this.setChecked( ! checked );
```
Comment (wdullaer) [inline library/src/main/java/com/wdullaer/swipeactionadapter/SwipeViewGroup.java]: Nitpicking mode: can you refactor this to: `this.setChecked(!checked);`

**Comment by wdullaer** [comment]
This is exactly what I had in mind myself. I just didn't get around to it yet.
Glad you can confirm that this solves the issue.

I've added some nitpicks on code style, just to keep everything consistent. If you can change those, I'll merge this right away.
